### ISSUE TITLE
Revolutions count

### ISSUE THREAD

**Issue by SuperLLN** [joedaniels29/10Clock#5]
Hi! 
It's possible to count the number of revolutions? I would like to use 10Clock and add a [days] field that I could increment or decrement by doing rotations.
Thanks for your help!

**Comment by joedaniels29** [comment]
Hey, um, Yes, its possible, though it wouldn't be the easiest thing in the world to do. 

The model for the control is just Radians on the unit circle. So the control does a transformation from the range [pi/2, 4pi + pi /2 ].  you can definitely change this, it would just take a bit of effort to make everything work nicely.

**Comment by P-huaizhi** [comment]
Have  10clock use  Objective-C?

**Comment by P-huaizhi** [comment]
I need a   Object-C  project.  Can you help me? 

Thanks for your help!

**Comment by joedaniels29** [comment]
@P-huaizhi in the future, its best to open a new issue....

That said, I don't think you should have much of an issue importing from an Obj-c project. it should work almost the same way. I've not used many only swift constructs, and the public api should be objc friendly I think. Can you describe the issue you're having?

**Comment by P-huaizhi** [comment]
@joedaniels29   YES!  The public api  is   functional, I  used  it  on my objc. 
Thanks your reply! thank you very much

**Comment by joedaniels29** [comment]
Good to hear! closing.
